# Development profile overrides
services:
  api:
    environment:
      - ENVIRONMENT=dev
      - LOG_LEVEL=debug
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/src --reload-dir /app/templates
