"""Profile cache

Revision ID: 182ba22c1a41
Revises: 003
Create Date: 2025-10-27 02:27:46.045134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '182ba22c1a41'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_cache_expires_at'), 'profile_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_profile_cache_fetched_at'), 'profile_cache', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_profile_cache_id'), 'profile_cache', ['id'], unique=False)
    op.create_index(op.f('ix_profile_cache_username'), 'profile_cache', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_cache_username'), table_name='profile_cache')
    op.drop_index(op.f('ix_profile_cache_id'), table_name='profile_cache')
    op.drop_index(op.f('ix_profile_cache_fetched_at'), table_name='profile_cache')
    op.drop_index(op.f('ix_profile_cache_expires_at'), table_name='profile_cache')
    op.drop_table('profile_cache')
    # ### end Alembic commands ###

