"""Add deleted field to Posts

Revision ID: bf3d203e53ac
Revises: 182ba22c1a41
Create Date: 2025-10-27 22:39:06.409808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3d203e53ac'
down_revision: Union[str, None] = '182ba22c1a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # Add the column with a default value first to handle existing rows
    op.add_column('posts', sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'deleted')
    # ### end Alembic commands ###

