"""add variant selection support

Revision ID: cc2c56a94c29
Revises: 4d9908c6590d
Create Date: 2025-11-02 20:24:37.057020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2c56a94c29'
down_revision: Union[str, None] = '4d9908c6590d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_templates_active'), 'post_templates', ['active'], unique=False)
    op.create_index(op.f('ix_post_templates_id'), 'post_templates', ['id'], unique=False)
    op.create_table('post_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('active', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('media_refs', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['post_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_variants_active'), 'post_variants', ['active'], unique=False)
    op.create_index(op.f('ix_post_variants_id'), 'post_variants', ['id'], unique=False)
    op.create_index(op.f('ix_post_variants_template_id'), 'post_variants', ['template_id'], unique=False)
    # Composite index for active variants lookup (partial index)
    op.create_index('idx_post_variants_template_active', 'post_variants', ['template_id', 'active'], unique=False, postgresql_where=sa.text('active = true'))
    op.create_table('variant_selection_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('planned_at', sa.DateTime(), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['publish_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['post_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['post_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_selection_history_id'), 'variant_selection_history', ['id'], unique=False)
    op.create_index(op.f('ix_variant_selection_history_job_id'), 'variant_selection_history', ['job_id'], unique=False)
    op.create_index(op.f('ix_variant_selection_history_planned_at'), 'variant_selection_history', ['planned_at'], unique=False)
    op.create_index(op.f('ix_variant_selection_history_schedule_id'), 'variant_selection_history', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_variant_selection_history_selected_at'), 'variant_selection_history', ['selected_at'], unique=False)
    op.create_index(op.f('ix_variant_selection_history_template_id'), 'variant_selection_history', ['template_id'], unique=False)
    op.create_index(op.f('ix_variant_selection_history_variant_id'), 'variant_selection_history', ['variant_id'], unique=False)
    # Composite indexes for efficient no-repeat window queries
    # Note: PostgreSQL can use these indexes efficiently for DESC queries even without explicit DESC ordering
    op.create_index('idx_variant_selection_template_date', 'variant_selection_history', ['template_id', 'selected_at'], unique=False)
    op.create_index('idx_variant_selection_template_variant', 'variant_selection_history', ['template_id', 'variant_id'], unique=False)
    op.create_index('idx_variant_selection_schedule_date', 'variant_selection_history', ['schedule_id', 'selected_at'], unique=False)
    op.add_column('publish_jobs', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.add_column('publish_jobs', sa.Column('selection_policy', sa.String(length=50), nullable=True))
    op.add_column('publish_jobs', sa.Column('selection_seed', sa.BigInteger(), nullable=True))
    op.add_column('publish_jobs', sa.Column('selected_at', sa.DateTime(), nullable=True))
    # Keep the unique constraint - do NOT drop it! It's critical for idempotency
    op.create_index(op.f('ix_publish_jobs_selection_seed'), 'publish_jobs', ['selection_seed'], unique=False)
    op.create_index(op.f('ix_publish_jobs_variant_id'), 'publish_jobs', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'publish_jobs', 'post_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.add_column('published_posts', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.alter_column('published_posts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_published_posts_variant_id'), 'published_posts', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'published_posts', 'post_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    # Add new columns with defaults for existing rows
    op.add_column('schedules', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('selection_policy', sa.String(length=50), nullable=True, server_default='RANDOM_UNIFORM'))
    op.add_column('schedules', sa.Column('no_repeat_window', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('schedules', sa.Column('no_repeat_scope', sa.String(length=20), nullable=True, server_default='template'))
    op.add_column('schedules', sa.Column('last_variant_pos', sa.Integer(), nullable=True))
    # Set defaults for existing rows before making NOT NULL
    op.execute("UPDATE schedules SET selection_policy = 'RANDOM_UNIFORM' WHERE selection_policy IS NULL")
    op.execute("UPDATE schedules SET no_repeat_window = 0 WHERE no_repeat_window IS NULL")
    op.execute("UPDATE schedules SET no_repeat_scope = 'template' WHERE no_repeat_scope IS NULL")
    # Now make columns NOT NULL
    op.alter_column('schedules', 'selection_policy', nullable=False, server_default='RANDOM_UNIFORM')
    op.alter_column('schedules', 'no_repeat_window', nullable=False, server_default='0')
    op.alter_column('schedules', 'no_repeat_scope', nullable=False, server_default='template')
    # Make post_id nullable (supports both legacy and new schedules)
    op.alter_column('schedules', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_schedules_template_id'), 'schedules', ['template_id'], unique=False)
    op.create_foreign_key(None, 'schedules', 'post_templates', ['template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_index(op.f('ix_schedules_template_id'), table_name='schedules')
    op.alter_column('schedules', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('schedules', 'last_variant_pos')
    op.drop_column('schedules', 'no_repeat_scope')
    op.drop_column('schedules', 'no_repeat_window')
    op.drop_column('schedules', 'selection_policy')
    op.drop_column('schedules', 'template_id')
    op.drop_constraint(None, 'published_posts', type_='foreignkey')
    op.drop_index(op.f('ix_published_posts_variant_id'), table_name='published_posts')
    op.alter_column('published_posts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('published_posts', 'variant_id')
    op.drop_constraint(None, 'publish_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_publish_jobs_variant_id'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_selection_seed'), table_name='publish_jobs')
    # Unique constraint should already exist, but restore it just in case
    # Note: This may fail if constraint already exists, but that's OK during downgrade
    op.create_unique_constraint(op.f('unique_schedule_planned_at'), 'publish_jobs', ['schedule_id', 'planned_at'], postgresql_nulls_not_distinct=False)
    op.drop_column('publish_jobs', 'selected_at')
    op.drop_column('publish_jobs', 'selection_seed')
    op.drop_column('publish_jobs', 'selection_policy')
    op.drop_column('publish_jobs', 'variant_id')
    op.drop_index('idx_variant_selection_schedule_date', table_name='variant_selection_history')
    op.drop_index('idx_variant_selection_template_variant', table_name='variant_selection_history')
    op.drop_index('idx_variant_selection_template_date', table_name='variant_selection_history')
    op.drop_index(op.f('ix_variant_selection_history_variant_id'), table_name='variant_selection_history')
    op.drop_index(op.f('ix_variant_selection_history_template_id'), table_name='variant_selection_history')
    op.drop_index(op.f('ix_variant_selection_history_selected_at'), table_name='variant_selection_history')
    op.drop_index(op.f('ix_variant_selection_history_schedule_id'), table_name='variant_selection_history')
    op.drop_index(op.f('ix_variant_selection_history_planned_at'), table_name='variant_selection_history')
    op.drop_index(op.f('ix_variant_selection_history_job_id'), table_name='variant_selection_history')
    op.drop_index(op.f('ix_variant_selection_history_id'), table_name='variant_selection_history')
    op.drop_table('variant_selection_history')
    op.drop_index('idx_post_variants_template_active', table_name='post_variants')
    op.drop_index(op.f('ix_post_variants_template_id'), table_name='post_variants')
    op.drop_index(op.f('ix_post_variants_id'), table_name='post_variants')
    op.drop_index(op.f('ix_post_variants_active'), table_name='post_variants')
    op.drop_table('post_variants')
    op.drop_index(op.f('ix_post_templates_id'), table_name='post_templates')
    op.drop_index(op.f('ix_post_templates_active'), table_name='post_templates')
    op.drop_table('post_templates')
    # ### end Alembic commands ###

